# Generated by Django 4.1.5 on 2023-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bestAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
